/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVentasRouteImport } from './routes/app.ventas'
import { Route as AppVencimientosRouteImport } from './routes/app.vencimientos'
import { Route as AppUsuariosRouteImport } from './routes/app.usuarios'
import { Route as AppTransferenciasRouteImport } from './routes/app.transferencias'
import { Route as AppPedidosRouteImport } from './routes/app.pedidos'
import { Route as AppPacientesRouteImport } from './routes/app.pacientes'
import { Route as AppInventarioRouteImport } from './routes/app.inventario'
import { Route as AppIngresosRouteImport } from './routes/app.ingresos'
import { Route as AppDispensacionRouteImport } from './routes/app.dispensacion'
import { Route as AppDepositosRouteImport } from './routes/app.depositos'
import { Route as AppDemoToolsRouteImport } from './routes/app.demo-tools'
import { Route as AppCatalogoRouteImport } from './routes/app.catalogo'
import { Route as AppAuditoriaRouteImport } from './routes/app.auditoria'
import { Route as AppAjustesRouteImport } from './routes/app.ajustes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVentasRoute = AppVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => AppRoute,
} as any)
const AppVencimientosRoute = AppVencimientosRouteImport.update({
  id: '/vencimientos',
  path: '/vencimientos',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppTransferenciasRoute = AppTransferenciasRouteImport.update({
  id: '/transferencias',
  path: '/transferencias',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosRoute = AppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppInventarioRoute = AppInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AppRoute,
} as any)
const AppIngresosRoute = AppIngresosRouteImport.update({
  id: '/ingresos',
  path: '/ingresos',
  getParentRoute: () => AppRoute,
} as any)
const AppDispensacionRoute = AppDispensacionRouteImport.update({
  id: '/dispensacion',
  path: '/dispensacion',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositosRoute = AppDepositosRouteImport.update({
  id: '/depositos',
  path: '/depositos',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoToolsRoute = AppDemoToolsRouteImport.update({
  id: '/demo-tools',
  path: '/demo-tools',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoRoute = AppCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppAjustesRoute = AppAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/ajustes': typeof AppAjustesRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/demo-tools': typeof AppDemoToolsRoute
  '/app/depositos': typeof AppDepositosRoute
  '/app/dispensacion': typeof AppDispensacionRoute
  '/app/ingresos': typeof AppIngresosRoute
  '/app/inventario': typeof AppInventarioRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/pedidos': typeof AppPedidosRoute
  '/app/transferencias': typeof AppTransferenciasRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/vencimientos': typeof AppVencimientosRoute
  '/app/ventas': typeof AppVentasRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/ajustes': typeof AppAjustesRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/demo-tools': typeof AppDemoToolsRoute
  '/app/depositos': typeof AppDepositosRoute
  '/app/dispensacion': typeof AppDispensacionRoute
  '/app/ingresos': typeof AppIngresosRoute
  '/app/inventario': typeof AppInventarioRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/pedidos': typeof AppPedidosRoute
  '/app/transferencias': typeof AppTransferenciasRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/vencimientos': typeof AppVencimientosRoute
  '/app/ventas': typeof AppVentasRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/ajustes': typeof AppAjustesRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/demo-tools': typeof AppDemoToolsRoute
  '/app/depositos': typeof AppDepositosRoute
  '/app/dispensacion': typeof AppDispensacionRoute
  '/app/ingresos': typeof AppIngresosRoute
  '/app/inventario': typeof AppInventarioRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/pedidos': typeof AppPedidosRoute
  '/app/transferencias': typeof AppTransferenciasRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/vencimientos': typeof AppVencimientosRoute
  '/app/ventas': typeof AppVentasRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/ajustes'
    | '/app/auditoria'
    | '/app/catalogo'
    | '/app/demo-tools'
    | '/app/depositos'
    | '/app/dispensacion'
    | '/app/ingresos'
    | '/app/inventario'
    | '/app/pacientes'
    | '/app/pedidos'
    | '/app/transferencias'
    | '/app/usuarios'
    | '/app/vencimientos'
    | '/app/ventas'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/ajustes'
    | '/app/auditoria'
    | '/app/catalogo'
    | '/app/demo-tools'
    | '/app/depositos'
    | '/app/dispensacion'
    | '/app/ingresos'
    | '/app/inventario'
    | '/app/pacientes'
    | '/app/pedidos'
    | '/app/transferencias'
    | '/app/usuarios'
    | '/app/vencimientos'
    | '/app/ventas'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/ajustes'
    | '/app/auditoria'
    | '/app/catalogo'
    | '/app/demo-tools'
    | '/app/depositos'
    | '/app/dispensacion'
    | '/app/ingresos'
    | '/app/inventario'
    | '/app/pacientes'
    | '/app/pedidos'
    | '/app/transferencias'
    | '/app/usuarios'
    | '/app/vencimientos'
    | '/app/ventas'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ventas': {
      id: '/app/ventas'
      path: '/ventas'
      fullPath: '/app/ventas'
      preLoaderRoute: typeof AppVentasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vencimientos': {
      id: '/app/vencimientos'
      path: '/vencimientos'
      fullPath: '/app/vencimientos'
      preLoaderRoute: typeof AppVencimientosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transferencias': {
      id: '/app/transferencias'
      path: '/transferencias'
      fullPath: '/app/transferencias'
      preLoaderRoute: typeof AppTransferenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pedidos': {
      id: '/app/pedidos'
      path: '/pedidos'
      fullPath: '/app/pedidos'
      preLoaderRoute: typeof AppPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pacientes': {
      id: '/app/pacientes'
      path: '/pacientes'
      fullPath: '/app/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventario': {
      id: '/app/inventario'
      path: '/inventario'
      fullPath: '/app/inventario'
      preLoaderRoute: typeof AppInventarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ingresos': {
      id: '/app/ingresos'
      path: '/ingresos'
      fullPath: '/app/ingresos'
      preLoaderRoute: typeof AppIngresosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dispensacion': {
      id: '/app/dispensacion'
      path: '/dispensacion'
      fullPath: '/app/dispensacion'
      preLoaderRoute: typeof AppDispensacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/depositos': {
      id: '/app/depositos'
      path: '/depositos'
      fullPath: '/app/depositos'
      preLoaderRoute: typeof AppDepositosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/demo-tools': {
      id: '/app/demo-tools'
      path: '/demo-tools'
      fullPath: '/app/demo-tools'
      preLoaderRoute: typeof AppDemoToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalogo': {
      id: '/app/catalogo'
      path: '/catalogo'
      fullPath: '/app/catalogo'
      preLoaderRoute: typeof AppCatalogoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auditoria': {
      id: '/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ajustes': {
      id: '/app/ajustes'
      path: '/ajustes'
      fullPath: '/app/ajustes'
      preLoaderRoute: typeof AppAjustesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAjustesRoute: typeof AppAjustesRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppCatalogoRoute: typeof AppCatalogoRoute
  AppDemoToolsRoute: typeof AppDemoToolsRoute
  AppDepositosRoute: typeof AppDepositosRoute
  AppDispensacionRoute: typeof AppDispensacionRoute
  AppIngresosRoute: typeof AppIngresosRoute
  AppInventarioRoute: typeof AppInventarioRoute
  AppPacientesRoute: typeof AppPacientesRoute
  AppPedidosRoute: typeof AppPedidosRoute
  AppTransferenciasRoute: typeof AppTransferenciasRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppVencimientosRoute: typeof AppVencimientosRoute
  AppVentasRoute: typeof AppVentasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAjustesRoute: AppAjustesRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppCatalogoRoute: AppCatalogoRoute,
  AppDemoToolsRoute: AppDemoToolsRoute,
  AppDepositosRoute: AppDepositosRoute,
  AppDispensacionRoute: AppDispensacionRoute,
  AppIngresosRoute: AppIngresosRoute,
  AppInventarioRoute: AppInventarioRoute,
  AppPacientesRoute: AppPacientesRoute,
  AppPedidosRoute: AppPedidosRoute,
  AppTransferenciasRoute: AppTransferenciasRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppVencimientosRoute: AppVencimientosRoute,
  AppVentasRoute: AppVentasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
