/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BackofficeRouteImport } from './routes/backoffice'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackofficeIndexRouteImport } from './routes/backoffice.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as BackofficeWorkspacesRouteImport } from './routes/backoffice.workspaces'
import { Route as BackofficeUsuariosRouteImport } from './routes/backoffice.usuarios'
import { Route as BackofficePanelEnVivoRouteImport } from './routes/backoffice.panel-en-vivo'
import { Route as BackofficeLoginRouteImport } from './routes/backoffice.login'
import { Route as BackofficeEsquemaRouteImport } from './routes/backoffice.esquema'
import { Route as AppVentasRouteImport } from './routes/app.ventas'
import { Route as AppVencimientosRouteImport } from './routes/app.vencimientos'
import { Route as AppUsuariosRouteImport } from './routes/app.usuarios'
import { Route as AppTransferenciasRouteImport } from './routes/app.transferencias'
import { Route as AppSalasRouteImport } from './routes/app.salas'
import { Route as AppPedidosRouteImport } from './routes/app.pedidos'
import { Route as AppPacientesRouteImport } from './routes/app.pacientes'
import { Route as AppListaPreciosRouteImport } from './routes/app.lista-precios'
import { Route as AppInventarioRouteImport } from './routes/app.inventario'
import { Route as AppIngresosRouteImport } from './routes/app.ingresos'
import { Route as AppDispensacionRouteImport } from './routes/app.dispensacion'
import { Route as AppDepositosRouteImport } from './routes/app.depositos'
import { Route as AppDemoToolsRouteImport } from './routes/app.demo-tools'
import { Route as AppCatalogoRouteImport } from './routes/app.catalogo'
import { Route as AppAuditoriaRouteImport } from './routes/app.auditoria'
import { Route as AppAjustesRouteImport } from './routes/app.ajustes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeIndexRoute = BackofficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const BackofficeWorkspacesRoute = BackofficeWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeUsuariosRoute = BackofficeUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficePanelEnVivoRoute = BackofficePanelEnVivoRouteImport.update({
  id: '/panel-en-vivo',
  path: '/panel-en-vivo',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeLoginRoute = BackofficeLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeEsquemaRoute = BackofficeEsquemaRouteImport.update({
  id: '/esquema',
  path: '/esquema',
  getParentRoute: () => BackofficeRoute,
} as any)
const AppVentasRoute = AppVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => AppRoute,
} as any)
const AppVencimientosRoute = AppVencimientosRouteImport.update({
  id: '/vencimientos',
  path: '/vencimientos',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppTransferenciasRoute = AppTransferenciasRouteImport.update({
  id: '/transferencias',
  path: '/transferencias',
  getParentRoute: () => AppRoute,
} as any)
const AppSalasRoute = AppSalasRouteImport.update({
  id: '/salas',
  path: '/salas',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosRoute = AppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppListaPreciosRoute = AppListaPreciosRouteImport.update({
  id: '/lista-precios',
  path: '/lista-precios',
  getParentRoute: () => AppRoute,
} as any)
const AppInventarioRoute = AppInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AppRoute,
} as any)
const AppIngresosRoute = AppIngresosRouteImport.update({
  id: '/ingresos',
  path: '/ingresos',
  getParentRoute: () => AppRoute,
} as any)
const AppDispensacionRoute = AppDispensacionRouteImport.update({
  id: '/dispensacion',
  path: '/dispensacion',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositosRoute = AppDepositosRouteImport.update({
  id: '/depositos',
  path: '/depositos',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoToolsRoute = AppDemoToolsRouteImport.update({
  id: '/demo-tools',
  path: '/demo-tools',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoRoute = AppCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppAjustesRoute = AppAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/backoffice': typeof BackofficeRouteWithChildren
  '/login': typeof LoginRoute
  '/app/ajustes': typeof AppAjustesRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/demo-tools': typeof AppDemoToolsRoute
  '/app/depositos': typeof AppDepositosRoute
  '/app/dispensacion': typeof AppDispensacionRoute
  '/app/ingresos': typeof AppIngresosRoute
  '/app/inventario': typeof AppInventarioRoute
  '/app/lista-precios': typeof AppListaPreciosRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/pedidos': typeof AppPedidosRoute
  '/app/salas': typeof AppSalasRoute
  '/app/transferencias': typeof AppTransferenciasRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/vencimientos': typeof AppVencimientosRoute
  '/app/ventas': typeof AppVentasRoute
  '/backoffice/esquema': typeof BackofficeEsquemaRoute
  '/backoffice/login': typeof BackofficeLoginRoute
  '/backoffice/panel-en-vivo': typeof BackofficePanelEnVivoRoute
  '/backoffice/usuarios': typeof BackofficeUsuariosRoute
  '/backoffice/workspaces': typeof BackofficeWorkspacesRoute
  '/app/': typeof AppIndexRoute
  '/backoffice/': typeof BackofficeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/ajustes': typeof AppAjustesRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/demo-tools': typeof AppDemoToolsRoute
  '/app/depositos': typeof AppDepositosRoute
  '/app/dispensacion': typeof AppDispensacionRoute
  '/app/ingresos': typeof AppIngresosRoute
  '/app/inventario': typeof AppInventarioRoute
  '/app/lista-precios': typeof AppListaPreciosRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/pedidos': typeof AppPedidosRoute
  '/app/salas': typeof AppSalasRoute
  '/app/transferencias': typeof AppTransferenciasRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/vencimientos': typeof AppVencimientosRoute
  '/app/ventas': typeof AppVentasRoute
  '/backoffice/esquema': typeof BackofficeEsquemaRoute
  '/backoffice/login': typeof BackofficeLoginRoute
  '/backoffice/panel-en-vivo': typeof BackofficePanelEnVivoRoute
  '/backoffice/usuarios': typeof BackofficeUsuariosRoute
  '/backoffice/workspaces': typeof BackofficeWorkspacesRoute
  '/app': typeof AppIndexRoute
  '/backoffice': typeof BackofficeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/backoffice': typeof BackofficeRouteWithChildren
  '/login': typeof LoginRoute
  '/app/ajustes': typeof AppAjustesRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/demo-tools': typeof AppDemoToolsRoute
  '/app/depositos': typeof AppDepositosRoute
  '/app/dispensacion': typeof AppDispensacionRoute
  '/app/ingresos': typeof AppIngresosRoute
  '/app/inventario': typeof AppInventarioRoute
  '/app/lista-precios': typeof AppListaPreciosRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/pedidos': typeof AppPedidosRoute
  '/app/salas': typeof AppSalasRoute
  '/app/transferencias': typeof AppTransferenciasRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/vencimientos': typeof AppVencimientosRoute
  '/app/ventas': typeof AppVentasRoute
  '/backoffice/esquema': typeof BackofficeEsquemaRoute
  '/backoffice/login': typeof BackofficeLoginRoute
  '/backoffice/panel-en-vivo': typeof BackofficePanelEnVivoRoute
  '/backoffice/usuarios': typeof BackofficeUsuariosRoute
  '/backoffice/workspaces': typeof BackofficeWorkspacesRoute
  '/app/': typeof AppIndexRoute
  '/backoffice/': typeof BackofficeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/backoffice'
    | '/login'
    | '/app/ajustes'
    | '/app/auditoria'
    | '/app/catalogo'
    | '/app/demo-tools'
    | '/app/depositos'
    | '/app/dispensacion'
    | '/app/ingresos'
    | '/app/inventario'
    | '/app/lista-precios'
    | '/app/pacientes'
    | '/app/pedidos'
    | '/app/salas'
    | '/app/transferencias'
    | '/app/usuarios'
    | '/app/vencimientos'
    | '/app/ventas'
    | '/backoffice/esquema'
    | '/backoffice/login'
    | '/backoffice/panel-en-vivo'
    | '/backoffice/usuarios'
    | '/backoffice/workspaces'
    | '/app/'
    | '/backoffice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/ajustes'
    | '/app/auditoria'
    | '/app/catalogo'
    | '/app/demo-tools'
    | '/app/depositos'
    | '/app/dispensacion'
    | '/app/ingresos'
    | '/app/inventario'
    | '/app/lista-precios'
    | '/app/pacientes'
    | '/app/pedidos'
    | '/app/salas'
    | '/app/transferencias'
    | '/app/usuarios'
    | '/app/vencimientos'
    | '/app/ventas'
    | '/backoffice/esquema'
    | '/backoffice/login'
    | '/backoffice/panel-en-vivo'
    | '/backoffice/usuarios'
    | '/backoffice/workspaces'
    | '/app'
    | '/backoffice'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/backoffice'
    | '/login'
    | '/app/ajustes'
    | '/app/auditoria'
    | '/app/catalogo'
    | '/app/demo-tools'
    | '/app/depositos'
    | '/app/dispensacion'
    | '/app/ingresos'
    | '/app/inventario'
    | '/app/lista-precios'
    | '/app/pacientes'
    | '/app/pedidos'
    | '/app/salas'
    | '/app/transferencias'
    | '/app/usuarios'
    | '/app/vencimientos'
    | '/app/ventas'
    | '/backoffice/esquema'
    | '/backoffice/login'
    | '/backoffice/panel-en-vivo'
    | '/backoffice/usuarios'
    | '/backoffice/workspaces'
    | '/app/'
    | '/backoffice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BackofficeRoute: typeof BackofficeRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof BackofficeIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/backoffice/workspaces': {
      id: '/backoffice/workspaces'
      path: '/workspaces'
      fullPath: '/backoffice/workspaces'
      preLoaderRoute: typeof BackofficeWorkspacesRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/usuarios': {
      id: '/backoffice/usuarios'
      path: '/usuarios'
      fullPath: '/backoffice/usuarios'
      preLoaderRoute: typeof BackofficeUsuariosRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/panel-en-vivo': {
      id: '/backoffice/panel-en-vivo'
      path: '/panel-en-vivo'
      fullPath: '/backoffice/panel-en-vivo'
      preLoaderRoute: typeof BackofficePanelEnVivoRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/login': {
      id: '/backoffice/login'
      path: '/login'
      fullPath: '/backoffice/login'
      preLoaderRoute: typeof BackofficeLoginRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/esquema': {
      id: '/backoffice/esquema'
      path: '/esquema'
      fullPath: '/backoffice/esquema'
      preLoaderRoute: typeof BackofficeEsquemaRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/app/ventas': {
      id: '/app/ventas'
      path: '/ventas'
      fullPath: '/app/ventas'
      preLoaderRoute: typeof AppVentasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vencimientos': {
      id: '/app/vencimientos'
      path: '/vencimientos'
      fullPath: '/app/vencimientos'
      preLoaderRoute: typeof AppVencimientosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transferencias': {
      id: '/app/transferencias'
      path: '/transferencias'
      fullPath: '/app/transferencias'
      preLoaderRoute: typeof AppTransferenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/salas': {
      id: '/app/salas'
      path: '/salas'
      fullPath: '/app/salas'
      preLoaderRoute: typeof AppSalasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pedidos': {
      id: '/app/pedidos'
      path: '/pedidos'
      fullPath: '/app/pedidos'
      preLoaderRoute: typeof AppPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pacientes': {
      id: '/app/pacientes'
      path: '/pacientes'
      fullPath: '/app/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lista-precios': {
      id: '/app/lista-precios'
      path: '/lista-precios'
      fullPath: '/app/lista-precios'
      preLoaderRoute: typeof AppListaPreciosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventario': {
      id: '/app/inventario'
      path: '/inventario'
      fullPath: '/app/inventario'
      preLoaderRoute: typeof AppInventarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ingresos': {
      id: '/app/ingresos'
      path: '/ingresos'
      fullPath: '/app/ingresos'
      preLoaderRoute: typeof AppIngresosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dispensacion': {
      id: '/app/dispensacion'
      path: '/dispensacion'
      fullPath: '/app/dispensacion'
      preLoaderRoute: typeof AppDispensacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/depositos': {
      id: '/app/depositos'
      path: '/depositos'
      fullPath: '/app/depositos'
      preLoaderRoute: typeof AppDepositosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/demo-tools': {
      id: '/app/demo-tools'
      path: '/demo-tools'
      fullPath: '/app/demo-tools'
      preLoaderRoute: typeof AppDemoToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalogo': {
      id: '/app/catalogo'
      path: '/catalogo'
      fullPath: '/app/catalogo'
      preLoaderRoute: typeof AppCatalogoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auditoria': {
      id: '/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ajustes': {
      id: '/app/ajustes'
      path: '/ajustes'
      fullPath: '/app/ajustes'
      preLoaderRoute: typeof AppAjustesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAjustesRoute: typeof AppAjustesRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppCatalogoRoute: typeof AppCatalogoRoute
  AppDemoToolsRoute: typeof AppDemoToolsRoute
  AppDepositosRoute: typeof AppDepositosRoute
  AppDispensacionRoute: typeof AppDispensacionRoute
  AppIngresosRoute: typeof AppIngresosRoute
  AppInventarioRoute: typeof AppInventarioRoute
  AppListaPreciosRoute: typeof AppListaPreciosRoute
  AppPacientesRoute: typeof AppPacientesRoute
  AppPedidosRoute: typeof AppPedidosRoute
  AppSalasRoute: typeof AppSalasRoute
  AppTransferenciasRoute: typeof AppTransferenciasRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppVencimientosRoute: typeof AppVencimientosRoute
  AppVentasRoute: typeof AppVentasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAjustesRoute: AppAjustesRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppCatalogoRoute: AppCatalogoRoute,
  AppDemoToolsRoute: AppDemoToolsRoute,
  AppDepositosRoute: AppDepositosRoute,
  AppDispensacionRoute: AppDispensacionRoute,
  AppIngresosRoute: AppIngresosRoute,
  AppInventarioRoute: AppInventarioRoute,
  AppListaPreciosRoute: AppListaPreciosRoute,
  AppPacientesRoute: AppPacientesRoute,
  AppPedidosRoute: AppPedidosRoute,
  AppSalasRoute: AppSalasRoute,
  AppTransferenciasRoute: AppTransferenciasRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppVencimientosRoute: AppVencimientosRoute,
  AppVentasRoute: AppVentasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BackofficeRouteChildren {
  BackofficeEsquemaRoute: typeof BackofficeEsquemaRoute
  BackofficeLoginRoute: typeof BackofficeLoginRoute
  BackofficePanelEnVivoRoute: typeof BackofficePanelEnVivoRoute
  BackofficeUsuariosRoute: typeof BackofficeUsuariosRoute
  BackofficeWorkspacesRoute: typeof BackofficeWorkspacesRoute
  BackofficeIndexRoute: typeof BackofficeIndexRoute
}

const BackofficeRouteChildren: BackofficeRouteChildren = {
  BackofficeEsquemaRoute: BackofficeEsquemaRoute,
  BackofficeLoginRoute: BackofficeLoginRoute,
  BackofficePanelEnVivoRoute: BackofficePanelEnVivoRoute,
  BackofficeUsuariosRoute: BackofficeUsuariosRoute,
  BackofficeWorkspacesRoute: BackofficeWorkspacesRoute,
  BackofficeIndexRoute: BackofficeIndexRoute,
}

const BackofficeRouteWithChildren = BackofficeRoute._addFileChildren(
  BackofficeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BackofficeRoute: BackofficeRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
